name: SignLocEdit
main: me.itsnathang.signloceditor.SignLocEdit
author: NathanG
version: 1.3
commands:
  signlocedit:
    aliases: [sle]
    description: Main command to edit a sign!
permisions:
  sle.admin:
    default: op
    description: Allows you to edit your signs.